#!/usr/bin/env bash
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
function Purpose() {
# begin block comment =============================
: <<'END'

#  Purpose:  tar the current folder and give the archive a useful name..


Read and edit these files. they may need editing.
    port number and project folder name -- C:\var\share203\incident295\deploy\rail263.conf  >>>>>  rename and edit.
    project name in this file. 
    ..
  
    
usage: run this from /srv/web/rail263


*******   Don't run with sudo..  *******


 cd /srv/web/rail263
 deploy/deploysh

end -- usage. 

END
# end block comment ===============================
}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#cd ;
date ; set +vx  ; set -vx ; # echo off, then echo on
#


prjname="rail263"
dpath="/srv/web/$prjname"

echo $prjname
echo $dpath

cd $dpath

mkdir -p shared/pids shared/sockets shared/log

sudo cp deploy/puma.conf /etc/init/puma.conf
sudo cp deploy/puma-manager.conf /etc/init/puma-manager.conf
cp deploy/puma.rb config/puma.rb


#old..
#sudo sh -c 'echo "$dpath" >> /etc/puma.conf'
#
# remove line containing  ???  and replace the line completely with the new text ...
# example.. sed 's/.*TEXT_TO_BE_REPLACED.*/This line is removed by the admin/'
# sudo sed -i "s/.*$dpath.*//$dpath/g" /etc/puma.conf



# add path to etc/puma.conf...
if grep --quiet "$dpath" /etc/puma.conf; then
  echo  the text exists.. do nothing..
else
  #  it's not found..
  sudo sh -c "echo $dpath >> /etc/puma.conf"
  echo added $dpath to puma.conf
fi



sudo cp  /etc/nginx/sites-available/$prjname.conf  /etc/nginx/sites-available/$prjname.conf$(date +"__%Y.%m.%d_%H.%M.%S").bk
# copy file into place --  from $prjname app folder /srv/web/$prjname
sudo cp  deploy/$prjname.conf /etc/nginx/sites-available/$prjname.conf
sudo ln -nfs /etc/nginx/sites-available/$prjname.conf /etc/nginx/sites-enabled/$prjname.conf

#https://github.com/sferik/rails_admin/issues/2515 -- Gradient has outdated direction syntax. New syntax is like `to left` instead of `right` #2515
sleep 4
bundle exec rake assets:precompile RAILS_ENV=production
sleep 3
bundle exec rake assets:precompile RAILS_ENV=production


sudo start puma-manager
sudo restart puma-manager
sudo service nginx restart



# http://stackoverflow.com/questions/4883891/ruby-on-rails-production-log-rotation
# http://www.thegeekstuff.com/2010/07/logrotate-examples
#
sudo tee /etc/logrotate.d/raillog_rail263 <<EOF
/srv/web/rail263/log/*.log {
    size=5k
    daily
    missingok
    rotate 62
    compress
    delaycompress
    notifempty
    copytruncate
}
EOF
#
