require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RentalRecordsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RentalRecord. As you add validations to RentalRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RentalRecordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all rental_records as @rental_records" do
      rental_record = RentalRecord.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rental_records)).to eq([rental_record])
    end
  end

  describe "GET #show" do
    it "assigns the requested rental_record as @rental_record" do
      rental_record = RentalRecord.create! valid_attributes
      get :show, {:id => rental_record.to_param}, valid_session
      expect(assigns(:rental_record)).to eq(rental_record)
    end
  end

  describe "GET #new" do
    it "assigns a new rental_record as @rental_record" do
      get :new, {}, valid_session
      expect(assigns(:rental_record)).to be_a_new(RentalRecord)
    end
  end

  describe "GET #edit" do
    it "assigns the requested rental_record as @rental_record" do
      rental_record = RentalRecord.create! valid_attributes
      get :edit, {:id => rental_record.to_param}, valid_session
      expect(assigns(:rental_record)).to eq(rental_record)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RentalRecord" do
        expect {
          post :create, {:rental_record => valid_attributes}, valid_session
        }.to change(RentalRecord, :count).by(1)
      end

      it "assigns a newly created rental_record as @rental_record" do
        post :create, {:rental_record => valid_attributes}, valid_session
        expect(assigns(:rental_record)).to be_a(RentalRecord)
        expect(assigns(:rental_record)).to be_persisted
      end

      it "redirects to the created rental_record" do
        post :create, {:rental_record => valid_attributes}, valid_session
        expect(response).to redirect_to(RentalRecord.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved rental_record as @rental_record" do
        post :create, {:rental_record => invalid_attributes}, valid_session
        expect(assigns(:rental_record)).to be_a_new(RentalRecord)
      end

      it "re-renders the 'new' template" do
        post :create, {:rental_record => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rental_record" do
        rental_record = RentalRecord.create! valid_attributes
        put :update, {:id => rental_record.to_param, :rental_record => new_attributes}, valid_session
        rental_record.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested rental_record as @rental_record" do
        rental_record = RentalRecord.create! valid_attributes
        put :update, {:id => rental_record.to_param, :rental_record => valid_attributes}, valid_session
        expect(assigns(:rental_record)).to eq(rental_record)
      end

      it "redirects to the rental_record" do
        rental_record = RentalRecord.create! valid_attributes
        put :update, {:id => rental_record.to_param, :rental_record => valid_attributes}, valid_session
        expect(response).to redirect_to(rental_record)
      end
    end

    context "with invalid params" do
      it "assigns the rental_record as @rental_record" do
        rental_record = RentalRecord.create! valid_attributes
        put :update, {:id => rental_record.to_param, :rental_record => invalid_attributes}, valid_session
        expect(assigns(:rental_record)).to eq(rental_record)
      end

      it "re-renders the 'edit' template" do
        rental_record = RentalRecord.create! valid_attributes
        put :update, {:id => rental_record.to_param, :rental_record => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested rental_record" do
      rental_record = RentalRecord.create! valid_attributes
      expect {
        delete :destroy, {:id => rental_record.to_param}, valid_session
      }.to change(RentalRecord, :count).by(-1)
    end

    it "redirects to the rental_records list" do
      rental_record = RentalRecord.create! valid_attributes
      delete :destroy, {:id => rental_record.to_param}, valid_session
      expect(response).to redirect_to(rental_records_url)
    end
  end

end
